# Generated by Django 3.2 on 2021-04-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_portal', '0002_auto_20210413_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
